Ide compliant change
opensearch-project/performance-analyzer-rca pull request #203
Opened 2022-08-12 18:25 UTC by kaushalmahi12

**Is your feature request related to a problem? Please provide an existing Issue # , or describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

**Describe the solution you are proposing**
A clear and concise description of what you want to happen.

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered.

**Additional context**
Add any other context or screenshots about the feature request here.

### Check List
- [ ] New functionality includes testing.
  - [x] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/performance-analyzer-rca/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2022-08-16 17:54 UTC, kkhatua requested changes
Recommend breaking this into multiple commits spanning groups of packages. 
That will make it easier to split the review across multiple eyes.

2022-08-16 23:30 UTC, kaushalmahi12 commented on config/rca_cluster_manager.conf
> +    "locus": "cluster_manager-node"
Yes You are right will make the change.

2022-08-16 23:30 UTC, kaushalmahi12 commented on src/main/java/org/opensearch/performanceanalyzer/metrics/AllMetrics.java
> +                    "ClusterManager_PendingQueueSize";
Ok

2022-08-16 23:30 UTC, kaushalmahi12 commented on src/main/java/org/opensearch/performanceanalyzer/metrics/PerformanceAnalyzerMetrics.java
> +            "cluster_manager_throttling_metrics";
Ok

2022-08-17 18:26 UTC, dzane17 commented on .github/workflows/gradle.yml
> +        repository: kaushalmahi12/performance-analyzer
Is this change temporary?

2022-08-17 19:01 UTC, kaushalmahi12 commented
I will break the commit into smaller ones and raise the PR against those. It will help the reviewers to review the changes without getting tired.

2022-08-17 19:01 UTC, closed without merging